version: '3.8'
services:
  minecraft:
    container_name: minecraft
    build:
      context: .
      dockerfile: ./.docker/minecraft/Dockerfile
    volumes:
      - ./:/server
    working_dir: '/server'
    ports:
    - "25565:25565/tcp"
    - "19132:19132/udp"
    - "25575:25575"
    - "8123:8123"
    networks:
    - network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
    - ./.docker/nginx:/etc/nginx/conf.d
    - ./dist:/dist
    - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - minecraft
    networks:
    - network

  certbot:
    container_name: certbot
    build:
      context: .
      dockerfile: ./.docker/certbot/Dockerfile
    volumes:
    - ./dist:/dist
    - /etc/letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 10d & wait $${!}; done;'"

networks:
  network:
    driver: bridge
