version: '3.8'
services:
  minecraft:
    container_name: minecraft
    build:
      context: .
      dockerfile: ./.docker/minecraft/Dockerfile
    volumes:
      - ./:/server
    working_dir: '/server'
    ports:
      - "25565:25565/tcp"
      - "19132:19132/udp"
      - "25575:25575"
      - "8123:8123"
    env_file:
      - .env
    networks:
      - network

  cron:
    container_name: cron
    build:
      context: .
      dockerfile: ./.docker/cron/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/server
      - ./logs:/logs
    working_dir: '/cron'

  backup:
    container_name: backup
    build:
      context: .
      dockerfile: ./.docker/backup/Dockerfile
    volumes:
      - ./world:/backup/world
      - ./world_nether:/backup/world_nether
      - ./world_the_end:/backup/world_the_end
      - ./.env:/backup/.env
    working_dir: '/backup'
    env_file:
      - .env

  route53:
    container_name: route53
    build:
      context: .
      dockerfile: ./.docker/route53/Dockerfile
    volumes:
      - ./.env:/route53/.env
    working_dir: '/route53'
    env_file:
      - .env

  batch:
    container_name: batch
    build:
      context: .
      dockerfile: ./.docker/batch/Dockerfile
    volumes:
      - ./logs:/batch/logs
      - ./.docker/batch:/batch/src
    working_dir: '/batch'
    env_file:
      - .env

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
      - ./.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - minecraft
    networks:
      - network

  certbot:
    container_name: certbot
    build:
      context: .
      dockerfile: ./.docker/certbot/Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    command: ["--version"]

networks:
  network:
    driver: bridge
