version: '3.8'
services:
  minecraft:
    container_name: minecraft
    build:
      context: .
      dockerfile: ./.docker/minecraft/Dockerfile
    volumes:
      - ./:/server
    working_dir: '/server'
    ports:
      - "25565:25565/tcp"
      - "19132:19132/udp"
      - "25575:25575"
      - "8123:8123"
    networks:
      - network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
      - ./.htpasswd:/etc/nginx/.htpasswd
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - minecraft
    networks:
      - network

  certbot:
    container_name: certbot
    build:
      context: .
      dockerfile: ./.docker/certbot/Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    command: ["--version"]


networks:
  network:
    driver: bridge
