name: Deploy Test
on:
  push:
    branches: master
jobs:
  Deploy-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          make chmod
          make up
